<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<url>
  <loc>https://www.haripavan.com/</loc>
  <lastmod>2019-05-07T12:37:06+00:00</lastmod>
</url>
<users>
	<user>37ED4AE15C7BC5EE14876BACA89B2252</user>
</users>

</urlset>
plugins: 
  - jekyll-sitemap
